config/routes.rb
App::Application.routes.draw do

  resources :bu_risk_mgts

  resources :third_party_risk_mgts

  resources :risk_exceptions

  resources :asset_risk_mgts

  resources :risk_classifications

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/risk_exception.rb
class RiskException < ActiveRecord::Base
  attr_accessible :Author, :Description, :Expiration, :Risk_Exception_Title
end

app/controllers/risk_exceptions_controller.rb
class RiskExceptionsController < ApplicationController
  # GET /risk_exceptions
  # GET /risk_exceptions.json
  def index
    @risk_exceptions = RiskException.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @risk_exceptions }
    end
  end

  # GET /risk_exceptions/1
  # GET /risk_exceptions/1.json
  def show
    @risk_exception = RiskException.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @risk_exception }
      format.pdf do
        pdf = Risk_exceptionsPdf.new(@risk_exception)
        send_data pdf.render , filename: "#{@risk_exception.Risk_Exception_Title}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /risk_exceptions/new
  # GET /risk_exceptions/new.json
  def new
    @risk_exception = RiskException.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @risk_exception }
    end
  end

  # GET /risk_exceptions/1/edit
  def edit
    @risk_exception = RiskException.find(params[:id])
  end

  # POST /risk_exceptions
  # POST /risk_exceptions.json
  def create
    @risk_exception = RiskException.new(params[:risk_exception])

    respond_to do |format|
      if @risk_exception.save
        format.html { redirect_to @risk_exception, notice: 'Risk exception was successfully created.' }
        format.json { render json: @risk_exception, status: :created, location: @risk_exception }
      else
        format.html { render action: "new" }
        format.json { render json: @risk_exception.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /risk_exceptions/1
  # PUT /risk_exceptions/1.json
  def update
    @risk_exception = RiskException.find(params[:id])

    respond_to do |format|
      if @risk_exception.update_attributes(params[:risk_exception])
        format.html { redirect_to @risk_exception, notice: 'Risk exception was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @risk_exception.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risk_exceptions/1
  # DELETE /risk_exceptions/1.json
  def destroy
    @risk_exception = RiskException.find(params[:id])
    @risk_exception.destroy

    respond_to do |format|
      format.html { redirect_to risk_exceptions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/risk_exceptions_helper.rb
module RiskExceptionsHelper
end

app/views/risk_exceptions/_form.html.erb
<%= form_for(@risk_exception) do |f| %>
  <% if @risk_exception.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@risk_exception.errors.count, "error") %> prohibited this risk_exception from being saved:</h2>

      <ul>
      <% @risk_exception.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Risk_Exception_Title %><br />
    <%= f.text_field :Risk_Exception_Title %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_field :Description %>
  </div>
  <div class="field">
    <%= f.label :Author %><br />
    <%= f.text_field :Author %>
  </div>
  <div class="field">
    <%= f.label :Expiration %><br />
    <%= f.date_select :Expiration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/risk_exceptions/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				<h1>Editing risk_exception</h1>
			<%= render 'form' %>
			
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/risk_exceptions/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#risk_exceptions" data-toggle="tab">Risk Exceptions</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

<h1>Listing Risk Exceptions</h1>

<table class="table table-bordered">
  <tr>
    <th>Risk exception title</th>
    <th>Description</th>
    <th>Author</th>
    <th>Expiration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @risk_exceptions.each do |risk_exception| %>
  <tr>
    <td><%= risk_exception.Risk_Exception_Title %></td>
    <td><%= risk_exception.Description %></td>
    <td><%= risk_exception.Author %></td>
    <td><%= risk_exception.Expiration %></td>
    <td><%= link_to 'Show', risk_exception %></td>
    <td><%= link_to 'Edit', edit_risk_exception_path(risk_exception) %></td>
    <td><%= link_to 'Destroy', risk_exception, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Risk exception', new_risk_exception_path , :class => "pure-button pure-button-primary"  %>
 </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/risk_exceptions/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
	<h1>New risk_Exceptions</h1>
	<%= render 'form' %>
			
<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/risk_exceptions/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">


<p id="notice"><%= notice %></p>

<p>
  <b>Risk exception title:</b>
  <%= @risk_exception.Risk_Exception_Title %>
</p>

<p>
  <b>Description:</b>
  <%= @risk_exception.Description %>
</p>

<p>
  <b>Author:</b>
  <%= @risk_exception.Author %>
</p>

<p>
  <b>Expiration:</b>
  <%= @risk_exception.Expiration %>
</p>


<%= link_to 'Edit', edit_risk_exception_path(@risk_exception) %> |
<%= link_to 'Back', risk_exceptions_path %>


<%= link_to "Show Report", risk_exception_path(@risk_exception, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_risk_exception_path(@risk_exception) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New RiskClassification', new_risk_exception_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>