config/routes.rb
App::Application.routes.draw do

  resources :bu_risk_mgts

  resources :third_party_risk_mgts

  resources :risk_exceptions

  resources :asset_risk_mgts

  resources :risk_classifications

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/asset_risk_mgt.rb
class AssetRiskMgt < ActiveRecord::Base
  attr_accessible :Applicable_Assets, :Applicable_Risk_Exceptions, :Compensating_Controls, :Risk_Classification, :Risk_Mitigation_Strategy, :Risk_Residual_Score, :Risk_Review_periodicity, :Risk_Score, :Risk_Title, :Threats, :Vulnerabilities
end

app/controllers/asset_risk_mgts_controller.rb
class AssetRiskMgtsController < ApplicationController
  # GET /asset_risk_mgts
  # GET /asset_risk_mgts.json
  def index
    @asset_risk_mgts = AssetRiskMgt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asset_risk_mgts }
    end
  end


  # GET /asset_risk_mgts/1
  # GET /asset_risk_mgts/1.json
  def show
    @asset_risk_mgt = AssetRiskMgt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erbs
      format.json { render json: @asset_risk_mgt }
      format.pdf do
        pdf = Asset_risk_mgtsPdf.new(@asset_risk_mgt)
        send_data pdf.render , filename: "#{@asset_risk_mgt.Risk_Title}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /asset_risk_mgts/new
  # GET /asset_risk_mgts/new.json
  def new
    @asset_risk_mgt = AssetRiskMgt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asset_risk_mgt }
    end
  end

  # GET /asset_risk_mgts/1/edit
  def edit
    @asset_risk_mgt = AssetRiskMgt.find(params[:id])
  end

  # POST /asset_risk_mgts
  # POST /asset_risk_mgts.json
  def create
    @asset_risk_mgt = AssetRiskMgt.new(params[:asset_risk_mgt])

    respond_to do |format|
      if @asset_risk_mgt.save
        format.html { redirect_to @asset_risk_mgt, notice: 'Asset risk mgt was successfully created.' }
        format.json { render json: @asset_risk_mgt, status: :created, location: @asset_risk_mgt }
      else
        format.html { render action: "new" }
        format.json { render json: @asset_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asset_risk_mgts/1
  # PUT /asset_risk_mgts/1.json
  def update
    @asset_risk_mgt = AssetRiskMgt.find(params[:id])

    respond_to do |format|
      if @asset_risk_mgt.update_attributes(params[:asset_risk_mgt])
        format.html { redirect_to @asset_risk_mgt, notice: 'Asset risk mgt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_risk_mgts/1
  # DELETE /asset_risk_mgts/1.json
  def destroy
    @asset_risk_mgt = AssetRiskMgt.find(params[:id])
    @asset_risk_mgt.destroy

    respond_to do |format|
      format.html { redirect_to asset_risk_mgts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asset_risk_mgts_helper.rb
module AssetRiskMgtsHelper
end

app/views/asset_risk_mgts/_form.html.erb
<%= form_for(@asset_risk_mgt) do |f| %>
  <% if @asset_risk_mgt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset_risk_mgt.errors.count, "error") %> prohibited this asset_risk_mgt from being saved:</h2>

      <ul>
      <% @asset_risk_mgt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
      <%= f.label :Risk_Title %><br />
    <%= f.text_field :Risk_Title %>
    </div>
    <div class="control-group">
      <%= f.label :Applicable_Assets %><br />
    <%= f.text_field :Applicable_Assets %>
    </div>
    <div class="control-group">
      <%= f.label :Threats %><br />
    <%= f.text_area :Threats %><br>
    <%= f.select :Threats ,[["",""],["competitors-compititive research","competitors-compititive research"],["competitors-patent infringment","competitors-patent infringment"],["competitors-dirty tricks","competitors-dirty tricks"],["competitors-illegal infiltration","competitors-illegal infiltration"]]  %>
    </div>
    <div class="control-group">
      <%= f.label :Vulnerabilities %><br />
    <%= f.text_field :Vulnerabilities %>
    </div>
    <div class="control-group">
       <%= f.label :Risk_Classification %><br />
    <%= f.text_area :Risk_Classification %>
    </div>
    <div class="control-group">
      <%= f.label :Risk_Score %><br />
    <%= f.number_field :Risk_Score %>
    </div>
<div class="control-group">
      <%= f.label :Risk_Mitigation_Strategy %><br />
    <%= f.text_field :Risk_Mitigation_Strategy %>
    </div>
<div class="control-group">
      <%= f.label :Compensating_Controls %><br />
    <%= f.text_field :Compensating_Controls %>
    </div>
<div class="control-group">
      <%= f.label :Risk_Residual_Score %><br />
    <%= f.number_field :Risk_Residual_Score %>
    </div>
<div class="control-group">
       <%= f.label :Applicable_Risk_Exceptions %><br />
    <%= f.text_field :Applicable_Risk_Exceptions %>
    </div>
<div class="control-group">
     <%= f.label :Risk_Review_periodicity %><br />
    <%= f.date_select :Risk_Review_periodicity %>
    </div>

<div class="control-group">
      <%= f.submit 'Create AssetRiskMgt', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', asset_risk_mgts_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/asset_risk_mgts/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
					<h1>Editing asset_risk_mgt</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/asset_risk_mgts/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#asset_risk_mgts" data-toggle="tab">Asset Risk Mgts</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">


<h1>Listing Asset Risk Mgts</h1>

<table class="table table-bordered">
  <tr>
    <th>Risk title</th>
    <th>Applicable assets</th>
    <th>Threats</th>
    <th>Vulnerabilities</th>
    <th>Risk classification</th>
    <th>Risk score</th>
    <th>Risk mitigation strategy</th>
    <th>Compensating controls</th>
    <th>Risk residual score</th>
    <th>Applicable risk exceptions</th>
    <th>Risk review periodicity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @asset_risk_mgts.each do |asset_risk_mgt| %>
  <tr>
    <td><%= asset_risk_mgt.Risk_Title %></td>
    <td><%= asset_risk_mgt.Applicable_Assets %></td>
    <td><%= asset_risk_mgt.Threats %></td>
    <td><%= asset_risk_mgt.Vulnerabilities %></td>
    <td><%= asset_risk_mgt.Risk_Classification %></td>
    <td><%= asset_risk_mgt.Risk_Score %></td>
    <td><%= asset_risk_mgt.Risk_Mitigation_Strategy %></td>
    <td><%= asset_risk_mgt.Compensating_Controls %></td>
    <td><%= asset_risk_mgt.Risk_Residual_Score %></td>
    <td><%= asset_risk_mgt.Applicable_Risk_Exceptions %></td>
    <td><%= asset_risk_mgt.Risk_Review_periodicity %></td>
    <td><%= link_to 'Show', asset_risk_mgt %></td>
    <td><%= link_to 'Edit', edit_asset_risk_mgt_path(asset_risk_mgt) %></td>
    <td><%= link_to 'Destroy', asset_risk_mgt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

                        <%= link_to 'New Asset risk mgt', new_asset_risk_mgt_path , :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/asset_risk_mgts/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<h1>New asset_risk_mgt</h1>
			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/asset_risk_mgts/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">

<p id="notice"><%= notice %></p>

<p>
  <b>Risk title:</b>
  <%= @asset_risk_mgt.Risk_Title %>
</p>

<p>
  <b>Applicable assets:</b>
  <%= @asset_risk_mgt.Applicable_Assets %>
</p>

<p>
  <b>Threats:</b>
  <%= @asset_risk_mgt.Threats1 %><br>
  <%= @asset_risk_mgt.Threats %>
</p>

<p>
  <b>Vulnerabilities:</b>
  <%= @asset_risk_mgt.Vulnerabilities %>
</p>

<p>
  <b>Risk classification:</b>
  <%= @asset_risk_mgt.Risk_Classification %>
</p>

<p>
  <b>Risk score:</b>
  <%= @asset_risk_mgt.Risk_Score %>
</p>

<p>
  <b>Risk mitigation strategy:</b>
  <%= @asset_risk_mgt.Risk_Mitigation_Strategy %>
</p>

<p>
  <b>Compensating controls:</b>
  <%= @asset_risk_mgt.Compensating_Controls %>
</p>

<p>
  <b>Risk residual score:</b>
  <%= @asset_risk_mgt.Risk_Residual_Score %>
</p>

<p>
  <b>Applicable risk exceptions:</b>
  <%= @asset_risk_mgt.Applicable_Risk_Exceptions %>
</p>

<p>
  <b>Risk review periodicity:</b>
  <%= @asset_risk_mgt.Risk_Review_periodicity %>
</p>

      <%= link_to "Show Report", asset_risk_mgt_path(@asset_risk_mgt, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_asset_risk_mgt_path(@asset_risk_mgt) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New RiskClassification', new_asset_risk_mgt_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>