config/routes.rb
App::Application.routes.draw do

  resources :bu_risk_mgts

  resources :third_party_risk_mgts

  resources :risk_exceptions

  resources :asset_risk_mgts

  resources :risk_classifications

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/third_party_risk_mgt.rb
class ThirdPartyRiskMgt < ActiveRecord::Base
  attr_accessible :Applicable_Assets, :Applicable_Risk_Exceptions, :Applicable_Third_Parties, :Compensating_Controls, :How_it_will_be_controled, :Risk_Classification, :Risk_Mitigation_Strategy, :Risk_Residual_Score, :Risk_Review_Periodicity, :Risk_Score, :Risk_Title, :Threats, :Vulnerabilities, :Why_are_assets_shared_with_this_TP
end

app/controllers/third_party_risk_mgts_controller.rb
class ThirdPartyRiskMgtsController < ApplicationController
  # GET /third_party_risk_mgts
  # GET /third_party_risk_mgts.json
  def index
    @third_party_risk_mgts = ThirdPartyRiskMgt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @third_party_risk_mgts }
    end
  end

  # GET /third_party_risk_mgts/1
  # GET /third_party_risk_mgts/1.json
  def show
    @third_party_risk_mgt = ThirdPartyRiskMgt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @third_party_risk_mgt }
      format.pdf do
        pdf = Third_party_risk_mgts_Pdf.new(@third_party_risk_mgt)
        send_data pdf.render , filename: "#{@third_party_risk_mgt.Risk_Title}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /third_party_risk_mgts/new
  # GET /third_party_risk_mgts/new.json
  def new
    @third_party_risk_mgt = ThirdPartyRiskMgt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @third_party_risk_mgt }
    end
  end

  # GET /third_party_risk_mgts/1/edit
  def edit
    @third_party_risk_mgt = ThirdPartyRiskMgt.find(params[:id])
  end

  # POST /third_party_risk_mgts
  # POST /third_party_risk_mgts.json
  def create
    @third_party_risk_mgt = ThirdPartyRiskMgt.new(params[:third_party_risk_mgt])

    respond_to do |format|
      if @third_party_risk_mgt.save
        format.html { redirect_to @third_party_risk_mgt, notice: 'Third party risk mgt was successfully created.' }
        format.json { render json: @third_party_risk_mgt, status: :created, location: @third_party_risk_mgt }
      else
        format.html { render action: "new" }
        format.json { render json: @third_party_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /third_party_risk_mgts/1
  # PUT /third_party_risk_mgts/1.json
  def update
    @third_party_risk_mgt = ThirdPartyRiskMgt.find(params[:id])

    respond_to do |format|
      if @third_party_risk_mgt.update_attributes(params[:third_party_risk_mgt])
        format.html { redirect_to @third_party_risk_mgt, notice: 'Third party risk mgt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @third_party_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /third_party_risk_mgts/1
  # DELETE /third_party_risk_mgts/1.json
  def destroy
    @third_party_risk_mgt = ThirdPartyRiskMgt.find(params[:id])
    @third_party_risk_mgt.destroy

    respond_to do |format|
      format.html { redirect_to third_party_risk_mgts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/third_party_risk_mgts_helper.rb
module ThirdPartyRiskMgtsHelper
end

app/views/third_party_risk_mgts/_form.html.erb
<%= form_for(@third_party_risk_mgt) do |f| %>
  <% if @third_party_risk_mgt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@third_party_risk_mgt.errors.count, "error") %> prohibited this third_party_risk_mgt from being saved:</h2>

      <ul>
      <% @third_party_risk_mgt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
    <%= f.label :Risk_Title %><br />
    <%= f.text_field :Risk_Title %>
  </div>
  <div class="control-group">
    <%= f.label :Applicable_Third_Parties %><br />
    <%= f.text_field :Applicable_Third_Parties %>
  </div>
  <div class="control-group">
    <%= f.label :Applicable_Assets %><br />
    <%= f.text_field :Applicable_Assets %>
  </div>
  <div class="control-group">
    <%= f.label :Why_are_assets_shared_with_this_TP %><br />
    <%= f.text_field :Why_are_assets_shared_with_this_TP %>
  </div>
  <div class="control-group">
    <%= f.label :How_it_will_be_controled %><br />
    <%= f.text_field :How_it_will_be_controled %>
  </div>
 <div class="control-group">
    <%= f.label :Threats %><br />
    <%= f.text_field :Threats %>
  </div>
  <div class="control-group">
    <%= f.label :Vulnerabilities %><br />
    <%= f.text_field :Vulnerabilities %>
  </div>
  <div class="control-group">
    <%= f.label :Risk_Classification %><br />
    <%= f.text_field :Risk_Classification %>
  </div>
  <div class="control-group">
    <%= f.label :Risk_Score %><br />
    <%= f.number_field :Risk_Score %>
  </div>
  <div class="control-group">
    <%= f.label :Risk_Mitigation_Strategy %><br />
    <%= f.text_field :Risk_Mitigation_Strategy %>
  </div>
 <div class="control-group">
    <%= f.label :Compensating_Controls %><br />
    <%= f.text_field :Compensating_Controls %>
  </div>
  <div class="control-group">
    <%= f.label :Risk_Residual_Score %><br />
    <%= f.number_field :Risk_Residual_Score %>
  </div>
  <div class="control-group">
    <%= f.label :Applicable_Risk_Exceptions %><br />
    <%= f.text_field :Applicable_Risk_Exceptions %>
  </div>
  <div class="control-group">
    <%= f.label :Risk_Review_Periodicity %><br />
    <%= f.date_select :Risk_Review_Periodicity %>
  </div>
   <div class="control-group">
      <%= f.submit 'Create Thirdparty', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', third_party_risk_mgts_path , :class => "pure-button pure-button-primary" %>
  </div>
<% end %>

</div>
</div>

app/views/third_party_risk_mgts/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				
			<%= render 'form' %>
			
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/third_party_risk_mgts/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#third_party_risk_mgts" data-toggle="tab">Third Party</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
<h1>Listing Third Party Risk Mgts</h1>
<table class="table table-bordered">
  <tr>
    <th>Risk title</th>
    <th>Applicable third parties</th>
    
  </tr>

<% @third_party_risk_mgts.each do |third_party_risk_mgt| %>
  <tr>
    <td><%= third_party_risk_mgt.Risk_Title %></td>
    <td><%= third_party_risk_mgt.Applicable_Third_Parties %></td>
    
    <td><%= link_to 'Show', third_party_risk_mgt %></td>
    <td><%= link_to 'Edit', edit_third_party_risk_mgt_path(third_party_risk_mgt) %></td>
    <td><%= link_to 'Destroy', third_party_risk_mgt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Third party risk mgt', new_third_party_risk_mgt_path , :class => "pure-button pure-button-primary"  %>
</div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/third_party_risk_mgts/new.html.erb
ml>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
	
	<%= render 'form' %>
			
<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/third_party_risk_mgts/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
<p id="notice"><%= notice %></p>

<p>
  <b>Risk title:</b>
  <%= @third_party_risk_mgt.Risk_Title %>
</p>

<p>
  <b>Applicable third parties:</b>
  <%= @third_party_risk_mgt.Applicable_Third_Parties %>
</p>

<p>
  <b>Applicable assets:</b>
  <%= @third_party_risk_mgt.Applicable_Assets %>
</p>

<p>
  <b>Why are assets shared with this tp:</b>
  <%= @third_party_risk_mgt.Why_are_assets_shared_with_this_TP %>
</p>

<p>
  <b>How it will be controled:</b>
  <%= @third_party_risk_mgt.How_it_will_be_controled %>
</p>

<p>
  <b>Threats:</b>
  <%= @third_party_risk_mgt.Threats %>
</p>

<p>
  <b>Vulnerabilities:</b>
  <%= @third_party_risk_mgt.Vulnerabilities %>
</p>

<p>
  <b>Risk classification:</b>
  <%= @third_party_risk_mgt.Risk_Classification %>
</p>

<p>
  <b>Risk score:</b>
  <%= @third_party_risk_mgt.Risk_Score %>
</p>

<p>
  <b>Risk mitigation strategy:</b>
  <%= @third_party_risk_mgt.Risk_Mitigation_Strategy %>
</p>

<p>
  <b>Compensating controls:</b>
  <%= @third_party_risk_mgt.Compensating_Controls %>
</p>

<p>
  <b>Risk residual score:</b>
  <%= @third_party_risk_mgt.Risk_Residual_Score %>
</p>

<p>
  <b>Applicable risk exceptions:</b>
  <%= @third_party_risk_mgt.Applicable_Risk_Exceptions %>
</p>

<p>
  <b>Risk review periodicity:</b>
  <%= @third_party_risk_mgt.Risk_Review_Periodicity %>
</p>

      <%= link_to "Show Report", third_party_risk_mgt_path(@third_party_risk_mgt, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_third_party_risk_mgt_path(@third_party_risk_mgt) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New ThirdParty', new_third_party_risk_mgt_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>