config/routes.rb
App::Application.routes.draw do

  resources :bu_risk_mgts

  resources :third_party_risk_mgts

  resources :risk_exceptions

  resources :asset_risk_mgts

  resources :risk_classifications

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/bu_risk_mgt.rb
class BuRiskMgt < ActiveRecord::Base
  attr_accessible :Applicable_Business_Units, :Applicable_Risk_Exceptions, :Compensating_Continuity_Plans, :Risk_Classification, :Risk_Mitigation_Strategy, :Risk_Residual_Score, :Risk_Review_periodicity, :Risk_Title, :Risk_score, :Threats, :Vulnerabilities, :What_is_the_business_impact_if_this_threats_materializes
end

app/controllers/bu_risk_mgts_controller.rb
class BuRiskMgtsController < ApplicationController
  # GET /bu_risk_mgts
  # GET /bu_risk_mgts.json
  def index
    @bu_risk_mgts = BuRiskMgt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bu_risk_mgts }
    end
  end

  # GET /bu_risk_mgts/1
  # GET /bu_risk_mgts/1.json
  def show
    @bu_risk_mgt = BuRiskMgt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bu_risk_mgt }
      format.pdf do
        pdf = Bu_risk_mgts_Pdf.new(@bu_risk_mgt)
        send_data pdf.render , filename: "#{@bu_risk_mgt.Risk_Title}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /bu_risk_mgts/new
  # GET /bu_risk_mgts/new.json
  def new
    @bu_risk_mgt = BuRiskMgt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bu_risk_mgt }
    end
  end

  # GET /bu_risk_mgts/1/edit
  def edit
    @bu_risk_mgt = BuRiskMgt.find(params[:id])
  end

  # POST /bu_risk_mgts
  # POST /bu_risk_mgts.json
  def create
    @bu_risk_mgt = BuRiskMgt.new(params[:bu_risk_mgt])

    respond_to do |format|
      if @bu_risk_mgt.save
        format.html { redirect_to @bu_risk_mgt, notice: 'Bu risk mgt was successfully created.' }
        format.json { render json: @bu_risk_mgt, status: :created, location: @bu_risk_mgt }
      else
        format.html { render action: "new" }
        format.json { render json: @bu_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bu_risk_mgts/1
  # PUT /bu_risk_mgts/1.json
  def update
    @bu_risk_mgt = BuRiskMgt.find(params[:id])

    respond_to do |format|
      if @bu_risk_mgt.update_attributes(params[:bu_risk_mgt])
        format.html { redirect_to @bu_risk_mgt, notice: 'Bu risk mgt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bu_risk_mgt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bu_risk_mgts/1
  # DELETE /bu_risk_mgts/1.json
  def destroy
    @bu_risk_mgt = BuRiskMgt.find(params[:id])
    @bu_risk_mgt.destroy

    respond_to do |format|
      format.html { redirect_to bu_risk_mgts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bu_risk_mgts_helper.rb
module BuRiskMgtsHelper
end

app/views/bu_risk_mgts/_form.html.erb
<%= form_for(@bu_risk_mgt) do |f| %>
  <% if @bu_risk_mgt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bu_risk_mgt.errors.count, "error") %> prohibited this bu_risk_mgt from being saved:</h2>

      <ul>
      <% @bu_risk_mgt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Risk_Title %><br />
    <%= f.text_field :Risk_Title %>
  </div>
  <div class="field">
    <%= f.label :Applicable_Business_Units %><br />
    <%= f.text_field :Applicable_Business_Units %>
  </div>
  <div class="field">
    <%= f.label :What_is_the_business_impact_if_this_threats_materializes? %><br />
    <%= f.text_field :What_is_the_business_impact_if_this_threats_materializes? %>
  </div>
  <div class="field">
    <%= f.label :Threats %><br />
    <%= f.text_field :Threats %>
  </div>
  <div class="field">
    <%= f.label :Vulnerabilities %><br />
    <%= f.text_field :Vulnerabilities %>
  </div>
  <div class="field">
    <%= f.label :Risk_Classification %><br />
    <%= f.text_field :Risk_Classification %>
  </div>
  <div class="field">
    <%= f.label :Risk_score %><br />
    <%= f.number_field :Risk_score %>
  </div>
  <div class="field">
    <%= f.label :Risk_Mitigation_Strategy %><br />
    <%= f.text_field :Risk_Mitigation_Strategy %>
  </div>
  <div class="field">
    <%= f.label :Compensating_Continuity_Plans %><br />
    <%= f.text_field :Compensating_Continuity_Plans %>
  </div>
  <div class="field">
    <%= f.label :Risk_Residual_Score %><br />
    <%= f.number_field :Risk_Residual_Score %>
  </div>
  <div class="field">
    <%= f.label :Applicable_Risk_Exceptions %><br />
    <%= f.text_field :Applicable_Risk_Exceptions %>
  </div>
  <div class="field">
    <%= f.label :Risk_Review_periodicity %><br />
    <%= f.date_select :Risk_Review_periodicity %>
  </div>
<div class="control-group">
      <%= f.submit 'Create BURiskMgt', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', bu_risk_mgts_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/bu_risk_mgts/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
					<h1>Editing bu_risk_mgt</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/bu_risk_mgts/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#bu_risk_mgts" data-toggle="tab">Asset Risk Mgts</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

<h1>Listing bu_risk_mgts</h1>

<table class="table table-bordered">
  <tr>
    <th>Risk title</th>
    <th>Applicable business units</th>
    <th>What is the business impact if this threats materializes?</th>
    <th>Threats</th>
    <th>Vulnerabilities</th>
    <th>Risk classification</th>
    <th>Risk score</th>
    <th>Risk mitigation strategy</th>
    <th>Compensating continuity plans</th>
    <th>Risk residual score</th>
    <th>Applicable risk exceptions</th>
    <th>Risk review periodicity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bu_risk_mgts.each do |bu_risk_mgt| %>
  <tr>
    <td><%= bu_risk_mgt.Risk_Title %></td>
    <td><%= bu_risk_mgt.Applicable_Business_Units %></td>
    <td><%= bu_risk_mgt.What_is_the_business_impact_if_this_threats_materializes? %></td>
    <td><%= bu_risk_mgt.Threats %></td>
    <td><%= bu_risk_mgt.Vulnerabilities %></td>
    <td><%= bu_risk_mgt.Risk_Classification %></td>
    <td><%= bu_risk_mgt.Risk_score %></td>
    <td><%= bu_risk_mgt.Risk_Mitigation_Strategy %></td>
    <td><%= bu_risk_mgt.Compensating_Continuity_Plans %></td>
    <td><%= bu_risk_mgt.Risk_Residual_Score %></td>
    <td><%= bu_risk_mgt.Applicable_Risk_Exceptions %></td>
    <td><%= bu_risk_mgt.Risk_Review_periodicity %></td>
    <td><%= link_to 'Show', bu_risk_mgt  %></td>
    <td><%= link_to 'Edit', edit_bu_risk_mgt_path(bu_risk_mgt) %></td>
    <td><%= link_to 'Destroy', bu_risk_mgt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
                        <%= link_to 'New Bu risk mgt', new_bu_risk_mgt_path , :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/bu_risk_mgts/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<h1>New bu_risk_mgt</h1>
			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/bu_risk_mgts/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">

<p id="notice"><%= notice %></p>

<p>
  <b>Risk title:</b>
  <%= @bu_risk_mgt.Risk_Title %>
</p>

<p>
  <b>Applicable business units:</b>
  <%= @bu_risk_mgt.Applicable_Business_Units %>
</p>

<p>
  <b>What is the business impact if this threats materializes?:</b>
  <%= @bu_risk_mgt.What_is_the_business_impact_if_this_threats_materializes? %>
</p>

<p>
  <b>Threats:</b>
  <%= @bu_risk_mgt.Threats %>
</p>

<p>
  <b>Vulnerabilities:</b>
  <%= @bu_risk_mgt.Vulnerabilities %>
</p>

<p>
  <b>Risk classification:</b>
  <%= @bu_risk_mgt.Risk_Classification %>
</p>

<p>
  <b>Risk score:</b>
  <%= @bu_risk_mgt.Risk_score %>
</p>

<p>
  <b>Risk mitigation strategy:</b>
  <%= @bu_risk_mgt.Risk_Mitigation_Strategy %>
</p>

<p>
  <b>Compensating continuity plans:</b>
  <%= @bu_risk_mgt.Compensating_Continuity_Plans %>
</p>

<p>
  <b>Risk residual score:</b>
  <%= @bu_risk_mgt.Risk_Residual_Score %>
</p>

<p>
  <b>Applicable risk exceptions:</b>
  <%= @bu_risk_mgt.Applicable_Risk_Exceptions %>
</p>

<p>
  <b>Risk review periodicity:</b>
  <%= @bu_risk_mgt.Risk_Review_periodicity %>
</p>

  <%= link_to "Show Report", bu_risk_mgt_path(@bu_risk_mgt, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_bu_risk_mgt_path(@bu_risk_mgt) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New Bu risk mgt', new_bu_risk_mgt_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>